BASEDIR	=	../../../..
CC	=	g++ -std=c++11
CXX	=	g++
CPPFLAGS	=	-Wall -I	${BASEDIR}/include
LDFLAGS	=	-L	${BASEDIR}/lib
LDLIBS = -limagem	-lotim -lmatrix -lpthread	#-lxfig

all:	main
main:	main.cpp

clean:
	rm	-f	main
