BASEDIR	=	../
CC	=	g++
CXX	=	g++
CPPFLAGS	=	-Wall -I	${BASEDIR}/include
LDFLAGS	=	-L	${BASEDIR}/lib
LDLIBS = -limagem	-lcamera

PROGRAMAS	=	teste_CampoVazio

all:	${PROGRAMAS}

clean:
	rm	-f	${PROGRAMAS}	*.txt	*.ppm
